- name: print user name
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: What is your username?
    private: false

  - name: password
    prompt: what is your password?
    private: false
  
  tasks: 
  - name: print username and password
    ansible.builtin.debug:
     msg: "hello userbame is: {{username}}, password is: {{password}}"
    
