- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.latest}}"
    loop:
    - { name: "nginx", state: "absent"}
    - { name: "mysql", state: "latest"}